# Generated by Django 4.1 on 2022-08-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='amount_in_cents',
            field=models.TextField(),
        ),
    ]
