# Generated by Django 4.1 on 2022-08-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_paymentrequest_amount_in_cents'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.TextField()),
                ('result', models.CharField(max_length=10)),
                ('errors', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StripeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='StripeResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_data', models.JSONField()),
            ],
        ),
    ]
