# Generated by Django 4.1 on 2022-08-20 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_paymentresponse_striperequest_striperesponse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StripeRequest',
            new_name='StripeLog',
        ),
        migrations.DeleteModel(
            name='StripeResponse',
        ),
    ]
