# Generated by Django 4.1 on 2022-08-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_apilog_stripelog_log_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('card_expiry_month', models.CharField(max_length=2)),
                ('card_expiry_year', models.CharField(max_length=4)),
                ('card_cvv', models.CharField(max_length=3)),
                ('amount_in_cents', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='PaymentRequest',
        ),
        migrations.DeleteModel(
            name='PaymentResponse',
        ),
    ]
