# Generated by Django 4.1 on 2022-08-21 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_apirequest_delete_paymentrequest_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIRequest',
        ),
    ]
